apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcc-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Deepak-du/MCC-Frontend-argo.git
    path: application.yaml
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

